/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary": "#59de9b",
        "tertiary-fixed": "#ffe16d",
        "tertiary-container": "#c8a900",
        "secondary-fixed": "#ffe088",
        "on-secondary": "#3c2f00",
        "outline-variant": "#3f4945",
        "secondary-fixed-dim": "#e9c349",
        "surface-variant": "#313633",
        "surface": "#0f1412",
        "secondary": "#e9c349",
        "primary-fixed-dim": "#59de9b",
        "on-primary": "#003921",
        "tertiary": "#e9c400",
        "on-tertiary-fixed": "#221b00",
        "on-secondary-fixed": "#241a00",
        "surface-container-low": "#181d1a",
        "surface-container": "#1c211e",
        "inverse-surface": "#dfe4e0",
        "on-error-container": "#ffdad6",
        "primary-container": "#004e2f",
        "tertiary-fixed-dim": "#e9c400",
        "primary-fixed": "#78fbb6",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#313633",
        "on-error": "#690005",
        "secondary-container": "#af8d11",
        "on-tertiary-fixed-variant": "#544600",
        "surface-container-high": "#262b29",
        "inverse-primary": "#006d43",
        "on-primary-container": "#3ec787",
        "inverse-on-surface": "#2c322f",
        "on-surface": "#dfe4e0",
        "surface-dim": "#0f1412",
        "background": "#0f1412",
        "surface-container-lowest": "#0a0f0d",
        "on-primary-fixed-variant": "#005232",
        "on-tertiary-container": "#4b3e00",
        "on-primary-fixed": "#002111",
        "outline": "#89938f",
        "on-surface-variant": "#bfc9c4",
        "surface-tint": "#59de9b",
        "error": "#ffb4ab",
        "on-tertiary": "#3a3000",
        "on-secondary-container": "#342800",
        "error-container": "#93000a",
        "surface-bright": "#353a38",
        "on-background": "#dfe4e0"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [],
}
